#include "ack_rst.h"
#include "../../include/config.h"
#include "../../include/hash.h"
#include "../../include/construct.h"
#include "../../include/protocol.h"

#include <string.h>
#include <arpa/inet.h>
#include <netinet/if_ether.h>
#include <netinet/ip6.h>
#include <netinet/tcp.h>
#include <linux/if_ether.h>

/*
 * Exact-address mode helper.
 *
 * When targets are generated by 6Genos, each target is already a full IPv6
 * address. These addresses do not contain the checksum suffix generated by
 * New-address-discovery.
 *
 * Therefore, if the response source address is found in exact_addr_table,
 * we should accept it directly instead of checking the murmur3 checksum.
 */
static int find_exact_addr_index(const struct in6_addr *addr,
                                 uint64_t *matched_index) {
    if (!addr || !matched_index) {
        return 0;
    }

    for (uint64_t i = 0; i < prefix_table_size; i++) {
        if (!exact_addr_flags[i]) {
            continue;
        }

        if (memcmp(addr, &exact_addr_table[i], sizeof(struct in6_addr)) == 0) {
            *matched_index = i;
            return 1;
        }
    }

    return 0;
}

/*
 * Bloom filter duplicate check.
 *
 * Return 1 if this address has already been seen.
 * Return 0 if this is a new address, and mark it as seen.
 */
static int is_duplicate_or_mark_seen(const struct in6_addr *addr) {
    uint32_t bloom_index_1 = murmur3(addr->s6_addr, 16, 0x12345678);
    uint32_t bloom_index_2 = murmur3(addr->s6_addr, 16, 0x87654321);

    uint32_t byte_index_1 = bloom_index_1 / 8;
    uint32_t bit_index_1  = bloom_index_1 % 8;
    uint32_t byte_index_2 = bloom_index_2 / 8;
    uint32_t bit_index_2  = bloom_index_2 % 8;

    if ((bloom_filter[byte_index_1] & (1 << bit_index_1)) &&
        (bloom_filter[byte_index_2] & (1 << bit_index_2))) {
        return 1;
    }

    bloom_filter[byte_index_1] |= (1 << bit_index_1);
    bloom_filter[byte_index_2] |= (1 << bit_index_2);

    return 0;
}

int ack_rst_build_probe(struct ethhdr *eth,
                        struct ip6_hdr *ip6,
                        struct tcphdr *tcp,
                        int index) {
    constructTCPv6Packet(eth, ip6, tcp, index);
    return 0;
}

int ack_rst_parse_response(const uint8_t *buffer,
                           ssize_t received_bytes,
                           struct in6_addr *target_ip,
                           uint64_t *prefix_index) {
    if (!buffer || !target_ip || !prefix_index) {
        return 0;
    }

    if (received_bytes <
        (ssize_t)(sizeof(struct ethhdr) +
                  sizeof(struct ip6_hdr) +
                  sizeof(struct tcphdr))) {
        return 0;
    }

    const struct ethhdr *eth_hdr = (const struct ethhdr *)buffer;
    if (ntohs(eth_hdr->h_proto) != ETH_P_IPV6) {
        return 0;
    }

    const struct ip6_hdr *ip6_hdr =
        (const struct ip6_hdr *)(buffer + sizeof(struct ethhdr));

    if (ip6_hdr->ip6_nxt != IPPROTO_TCP) {
        return 0;
    }

    const struct tcphdr *tcp_hdr =
        (const struct tcphdr *)(buffer +
                                sizeof(struct ethhdr) +
                                sizeof(struct ip6_hdr));

    /*
     * ACK-RST probing mainly treats TCP RST as a valid response.
     */
    if (!tcp_hdr->rst) {
        return 0;
    }

    *target_ip = ip6_hdr->ip6_src;

    /*
     * Case 1: exact-address mode.
     *
     * This is the key fix for 6Genos integration.
     *
     * 6Genos gives real candidate IPv6 addresses directly.
     * These addresses do not satisfy the checksum rule:
     *
     *     last 32 bits == murmur3(first 96 bits)
     *
     * Therefore, we first check whether the response source address exactly
     * matches one address in exact_addr_table. If yes, accept it directly.
     */
    uint64_t exact_index = 0;
    if (find_exact_addr_index(target_ip, &exact_index)) {
        if (is_duplicate_or_mark_seen(target_ip)) {
            return 0;
        }

        *prefix_index = exact_index;
        return 1;
    }

    /*
     * Case 2: original prefix-generation mode.
     *
     * In this mode, New-address-discovery generated the target address itself.
     * The last 32 bits of the address contain the murmur3 checksum.
     * So we keep the original checksum validation logic here.
     */
    uint32_t embedded_checksum;
    memcpy(&embedded_checksum, target_ip->s6_addr + 12, sizeof(uint32_t));
    embedded_checksum = ntohl(embedded_checksum);

    uint32_t computed_checksum =
        murmur3(target_ip->s6_addr, 12, 0x11112222);

    if (embedded_checksum != computed_checksum) {
        return 0;
    }

    uint32_t seq = ntohl(tcp_hdr->seq);
    *prefix_index = seq >> 8;

    if (*prefix_index >= prefix_table_size) {
        return 0;
    }

    if (is_duplicate_or_mark_seen(target_ip)) {
        return 0;
    }

    return 1;
}

protocol_t ack_rst_protocol = {
    .name = "ack_rst",

    /*
     * These casts are used to match the generic protocol_t interface.
     * The actual L4 pointer is still treated as struct tcphdr * inside
     * ack_rst_build_probe().
     */
    .build_probe =
        (int (*)(struct ethhdr *, struct ip6_hdr *, void *, int))
        ack_rst_build_probe,

    .parse_response =
        (int (*)(uint8_t *, ssize_t, struct in6_addr *, uint64_t *))
        ack_rst_parse_response
};

/* automatic registration */
__attribute__((constructor))
static void register_ack_rst(void) {
    register_protocol(&ack_rst_protocol);
}